name: PyInstaller Windows

on:
  push:
      branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile app/app.spec
    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: Image Tools Windows
        path: dist/Image Tools.exe
